project_id = "dudzxsnrybsgezodylwf"

[functions.paystack-webhook]
verify_jwt = false

[functions.paystack-reconcile]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.send-renewal-reminders]
verify_jwt = false

[functions.verify-identity]
verify_jwt = false